name: p2p
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  pin_code_fields: ^7.4.0

  alice: ^0.2.5
  dio: ^4.0.6
  dartz: ^0.10.1
  dio_http_cache: ^0.3.0

  firebase_core: ^1.23.0
  firebase_analytics: ^9.3.6

  flutter_bloc: ^7.3.3
  bloc_concurrency: ^0.1.0
  equatable: ^2.0.5
  pedantic: ^1.11.1
  shared_preferences: ^2.0.15
  
  get: ^4.6.3

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/user.png
    - assets/].png
    - assets/flag.png
    - assets/Gmail.png
    - assets/Facebook.png
    - assets/Google.png
    - assets/Rectangle.png
    - assets/Group.png
    - assets/offer.png
    - assets/map.png
    - assets/fastfood.png
    - assets/splash.png
    - assets/ad.png
    - assets/Search.png
    - assets/Notification.png
    - assets/Group.png
    - assets/shop.png
    - assets/wecon.png
    - assets/dp.png
    - assets/mosque.png
    - assets/map.png
    - assets/offer.png
    - assets/news.png
    - assets/compass.png
    - assets/discount.png
    - assets/home.png
    - assets/menu.png
    - assets/user_s.png
    - assets/offer_banner.png
    - assets/act_group.png
    - assets/loading.png
    - assets/slider_img.png
    - assets/slider_img_two.png
    - assets/top_offers.png
    - assets/meeting.png
    - assets/events.png
    - assets/card.png
    - assets/life.png
    - assets/meetings.png
    - assets/arcticons_lounge.png
    - assets/events_screen.png
    - assets/card_screen.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family: Questrial
    fonts:
      - asset: fonts/Questrial-Regular.ttf
  - family: Poppins
    fonts:
      - asset: fonts/Poppins-Regular.ttf
  - family: Quantico
    fonts:
      - asset: fonts/Quantico-Regular.otf


  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
